name: Sync with MrBElga Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório do Paulo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar o repositório de destino
        run: |
          git remote add target https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/MrBElga/ComputerGraphics.git
          git fetch target

      - name: Copiar mudanças para o repositório de destino
        run: |
          rsync -av --exclude='.git' ./ ./  # Copia os arquivos para o repositório de destino
          git add .
          git commit -m "Sync automático do repo do Paulo" || echo "Nenhuma mudança para commitar"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/MrBElga/ComputerGraphics.git main
