name: Sync with MrBElga Repo

on:
  push:
    branches:
      - main  # Altere se o branch principal for outro

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório do Paulo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clonar repositório de destino (MrBElga/ComputerGraphics)
        run: |
          git config --global url."https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
          git clone https://github.com/MrBElga/ComputerGraphics.git target-repo
          cd target-repo
          git config user.name "MrBElga"
          git config user.email "danieleliasrumin@gmail.com"

      - name: Copiar mudanças para o repositório de destino
        run: |
          rsync -av --exclude='.git' . target-repo/
          cd target-repo
          git add .
          git commit -m "Sync automático do repo do Paulo" || echo "Nenhuma mudança para commitar"
          git push origin main
