name: Sync with MrBElga Repo

on:
  push:
    branches:
      - main  # Altere se o branch principal for outro

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório do Paulo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clonar repositório de destino (MrBElga/ComputerGraphics)
        run: |
          # Remove o diretório de trabalho atual para evitar conflitos
          rm -rf *
          rm -rf .git
          
          # Clona o repositório de destino diretamente no diretório de trabalho
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/MrBElga/ComputerGraphics.git .
          git config user.name "MrBElga"
          git config user.email "danieleliasrumin@gmail.com"

      - name: Copiar mudanças do repositório de origem para o destino
        run: |
          # Copia os arquivos do repositório de origem para o diretório de trabalho
          rsync -av --exclude='.git' ../repo-origem/ .
          
          # Adiciona as mudanças e faz o commit
          git add .
          git commit -m "Sync automático do repo do Paulo" || echo "Nenhuma mudança para commitar"
          git push origin main
